project:
  type: website
  output-dir: docs

website:
  title: "Jiuru Lyu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: notes.qmd
        text: Notes
      - href: photo.qmd
        text: Photograph

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

