---
title: "Class Notes"
---

### High School Level Math

- [IB Math AA HL Notes](notes/IBMath.qmd)

### College Level Math

#### Math Fundamentals

- [Calculus II](notes/Calc2.qmd)
- [Multivariable Calculus/Advanced Calculus/Calculus III](notes/Calc3.qmd)
- [Linear Algebra](notes/LA.qmd)
- [Mathematical Proofs](notes/Proofs.qmd)
- [Proof Practice](notes/ProofPractice.qmd)

#### Applied Mathematics

- [Ordinary Differential Equations](notes/ODE.qmd)
- [Nonlinear Optimization](notes/NonlinearOpt.qmd)
- [Undergraduate-Level Numerical Analysis](notes/NA1.qmd)
- [Numerical ODEs and PDEs](notes/NumericalDEs.qmd)
- [PhD-Level Numerical Analysis I (Numerical Linear Algebra)](notes/NA2.qmd)
- [PhD-Level Numerical Analysis II](notes/NA3.qmd)


#### Pure Mathematics
- [Linear Algebra Done Right](notes/LADR.qmd)
- [Real Analysis](notes/RealAnalysis.qmd)

#### Data Science, Statistics, and Causal Inference

- [Introduction to Causal Inference](https://jrlyu.github.io/qtm110.io/)
- [Google Data Analytics Learning Notes](https://jrlyu.github.io/google_analytics.io/)
- [Mathematical Statistics -- Propability Theory](notes/Probability.qmd)
- [Mathematical Statistics -- Statistical Inference](notes/Inference.qmd)
- Causal Designs and Inference
- [Machine Learning](notes/cs334.qmd)

### Computer Science

- [Object-Oriented Programming & Introduction to Data Structures](notes/cs171.qmd)
- [Introduction to Data Structure and Algorithms](notes/cs253.qmd)
- [Database Systems](notes/cs377.qmd)


### Other Fields

- [Introduction to Sociology](https://jrlyu.github.io/intro_to_socio.io/)

